repos:
  - repo: https://github.com/pycqa/pylint
    rev: v4.0.3
    hooks:
      - id: pylint
        args:
          - "-rn"
          - "-sn"
          - "--rcfile=.pylintrc"
        additional_dependencies:
          - pylint==4.0.3
